"""
PQR file parser for PySTARC.
PQR format (AMBER-style):
  ATOM  serial  name  resName  resSeq  x  y  z  charge  radius
"""

from __future__ import annotations
from pystarc.structures.molecules import Atom, Molecule
from typing import List, Optional
from pathlib import Path


def parse_pqr(path: str | Path) -> Molecule:
    """Read a .pqr file and return a Molecule."""
    path = Path(path)
    mol = Molecule(name=path.stem)
    index = 0
    with open(path) as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("REMARK") or line.startswith("END"):
                continue
            record = line[:6].strip()
            if record not in ("ATOM", "HETATM"):
                continue
            try:
                parts = line.split()
                # Try positional first, fall back to split
                atom = Atom(
                    index=index,
                    name=parts[2],
                    residue_name=parts[3],
                    residue_index=(
                        int(parts[4]) if parts[4].lstrip("-").isdigit() else 0
                    ),
                    chain="A",
                    x=float(parts[5]),
                    y=float(parts[6]),
                    z=float(parts[7]),
                    charge=float(parts[8]),
                    radius=float(parts[9]),
                )
                mol.atoms.append(atom)
                index += 1
            except (IndexError, ValueError):
                continue
    return mol


def write_pqr(mol: Molecule, path: str | Path) -> None:
    """Write a Molecule to a .pqr file."""
    path = Path(path)
    with open(path, "w") as fh:
        fh.write(f"REMARK  Generated by PySTARC  molecule={mol.name}\n")
        for i, a in enumerate(mol.atoms):
            name = a.name if a.name else "X"
            resname = a.residue_name if a.residue_name else "UNK"
            fh.write(
                f"ATOM  {i+1:5d}  {name:<4s} {resname:<4s} "
                f"{a.residue_index:4d}    "
                f"{a.x:8.3f}{a.y:8.3f}{a.z:8.3f}  "
                f"{a.charge:7.4f} {a.radius:6.4f}\n"
            )
        fh.write("END\n")
