"""
PySTARC GHO ghost atom utilities

This module provides the GHO (ghost atom or dummy atom) infrastructure that
PySTARC uses to evaluate distance-based reaction criteria. Without it, PySTARC
falls back to a centroid distance criterion, which gives wrong k_on values.

The parsers parse_rxns_xml and parse_ghost_atoms_from_input read ghost atom
specifications from the reactions XML and the input XML respectively. The
function inject_gho_from_manual injects ghost atoms by hand when pre-computed
positions are not available from the reactions XML. The geometry helpers
gho_world_position and gho_criterion_distance evaluate the GHO reaction
criterion at runtime, and GHOReactionCriterion is the runtime reaction-criterion
class that ties these together.
"""

from __future__ import annotations
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
import xml.etree.ElementTree as ET
import numpy as np


# Data structures
@dataclass
class GHOAtom:
    """
    A single ghost atom (GHO or dummy atom) position. The field pos_rel holds
    the position relative to the hydrodynamic centre of the molecule, and
    atom_index is the 0-based atom index within the dummy molecule.
    """

    atom_index: int
    pos_rel: np.ndarray  # position in Å as a length-3 vector, relative to the hydrodynamic centre


@dataclass
class DummyMolecule:
    """
    A named dummy molecule containing one or more GHO atoms, corresponding to a
    <dummy> block in the simulation XML. The field name is the dummy molecule
    name, for example "gho_receptor". The field core_name is the name of the
    rigid core it belongs to. The field atoms is the list of GHOAtom objects,
    with positions relative to the hydrodynamic centre of the core.
    """

    name: str
    core_name: str
    atoms: List[GHOAtom] = field(default_factory=list)


# Parser
def parse_rxns_xml(rxns_xml_path: str) -> List[DummyMolecule]:
    """
    Parse a reactions XML file and extract all dummy molecule definitions.

    The reactions XML used by the reference implementation has the structure

        <reactions>
          <reaction>
            <name> ... </name>
            <criterion>
              <n_needed> 2 </n_needed>
              <pair>
                <atom1> mol1 atom_idx distance </atom1>
                <atom2> mol2 atom_idx distance </atom2>
              </pair>
            </criterion>
          </reaction>
        </reactions>

    The <dummy> blocks appear in the simulation XML generated by bd_top, not
    directly in rxns.xml. PySTARC instead reads the GHO positions from the
    format used in our pystarc_input.xml <ghost_atoms> section, which lists one
    line of "mol_idx,atom_idx,distance" per ghost atom. This function also
    handles rxns files where dummy positions are encoded as comment lines or as
    explicit <dummy> blocks. It returns a list of DummyMolecule, which may be
    empty if no dummies are found.
    """
    dummies: List[DummyMolecule] = []
    try:
        tree = ET.parse(rxns_xml_path)
        root = tree.getroot()
    except Exception as e:
        raise ValueError(f"Cannot parse rxns XML {rxns_xml_path}: {e}")
    # Look for <dummy> blocks anywhere in the tree.
    for dummy_node in root.iter("dummy"):
        name = _text(dummy_node, "name", required=True)
        core_name = _text(dummy_node, "core", required=True)
        atoms_txt = _text(dummy_node, "atoms", required=False) or ""
        dm = DummyMolecule(name=name, core_name=core_name)
        # Parse the atom positions, one atom per line in the form "atom_idx x y z".
        for line in atoms_txt.strip().splitlines():
            parts = line.strip().split()
            if len(parts) >= 4:
                try:
                    idx = int(parts[0])
                    x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                    dm.atoms.append(
                        GHOAtom(atom_index=idx, pos_rel=np.array([x, y, z]))
                    )
                except ValueError:
                    continue
        if dm.atoms:
            dummies.append(dm)
    return dummies


def parse_ghost_atoms_from_input(
    ghost_atoms_text: str, mol_positions: Dict[int, np.ndarray]
) -> List[GHOAtom]:
    """
    Parse the <ghost_atoms> section from a pystarc_input.xml file. Each line has
    the form "mol_index, atom_index, distance_cutoff", for example

        3220,0,17.0
        3221,0,10.0

    This is the manual override format used when bd_top is not available. The
    ghost atom position is taken as the centroid of the molecule, offset by the
    specified distance along +z as a placeholder.
    """
    atoms = []
    for line in ghost_atoms_text.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) >= 3:
            try:
                mol_idx = int(parts[0])
                atom_idx = int(parts[1])
                # The distance field is the reaction criterion, not a position.
                pos = mol_positions.get(mol_idx, np.zeros(3))
                atoms.append(GHOAtom(atom_index=atom_idx, pos_rel=pos.copy()))
            except ValueError:
                continue
    return atoms


# GHO position computation
def gho_world_position(
    gho_atom: GHOAtom,
    rotation_mat: np.ndarray,  # 3x3 rotation matrix
    translation: np.ndarray,  # length-3 translation vector
) -> np.ndarray:
    """
    Compute the world-frame position of a GHO atom given the current rigid body
    pose. The argument gho_atom is a GHOAtom whose pos_rel is expressed in the
    frame of the molecular core. The argument rotation_mat is the current 3x3
    rotation matrix of the molecule, and translation is its current length-3
    translation, that is the position of its centroid.
    """
    return rotation_mat @ gho_atom.pos_rel + translation


def gho_criterion_distance(
    gho1: GHOAtom,
    rot1: np.ndarray,
    trans1: np.ndarray,
    gho2: GHOAtom,
    rot2: np.ndarray,
    trans2: np.ndarray,
) -> float:
    """
    Return the distance between two GHO atoms in the world frame. This is used by
    the reaction criterion evaluator.
    """
    p1 = gho_world_position(gho1, rot1, trans1)
    p2 = gho_world_position(gho2, rot2, trans2)
    return float(np.linalg.norm(p2 - p1))




def inject_gho_from_manual(
    ghost_atoms_spec: str,
    mol1_positions: np.ndarray,
    mol2_positions: np.ndarray,
    mol1_hydro_cen: np.ndarray,
    mol2_hydro_cen: np.ndarray,
) -> Tuple[List[GHOAtom], List[GHOAtom]]:
    """
    Build GHO atoms from a manual specification in pystarc_input.xml format,
    such as

        <ghost_atoms>
            3220,0,17.0
            3221,0,10.0
        </ghost_atoms>

    Each line has the form "mol_atom_index, reaction_atom_index,
    distance_threshold". The GHO position is taken as the mean position of all
    atoms in the molecule, that is its centroid, relative to the hydrodynamic
    centre. The function returns the pair (gho_atoms_mol1, gho_atoms_mol2).
    """
    mol1_ghos: List[GHOAtom] = []
    mol2_ghos: List[GHOAtom] = []
    n1 = len(mol1_positions)
    n2 = len(mol2_positions)
    centroid1 = mol1_positions.mean(axis=0) if n1 > 0 else np.zeros(3)
    centroid2 = mol2_positions.mean(axis=0) if n2 > 0 else np.zeros(3)
    for line in ghost_atoms_spec.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) < 2:
            continue
        try:
            global_atom_idx = int(parts[0])
            rxn_atom_idx = int(parts[1])

            # Decide which molecule this atom belongs to.
            if global_atom_idx < n1:
                # The atom is in molecule 1, the receptor.
                pos_abs = (
                    mol1_positions[global_atom_idx]
                    if global_atom_idx < n1
                    else centroid1
                )
                pos_rel = pos_abs - mol1_hydro_cen
                mol1_ghos.append(GHOAtom(atom_index=rxn_atom_idx, pos_rel=pos_rel))
            else:
                # The atom is in molecule 2, the ligand.
                local_idx = global_atom_idx - n1
                pos_abs = mol2_positions[local_idx] if local_idx < n2 else centroid2
                pos_rel = pos_abs - mol2_hydro_cen
                mol2_ghos.append(GHOAtom(atom_index=rxn_atom_idx, pos_rel=pos_rel))
        except (ValueError, IndexError):
            continue
    return mol1_ghos, mol2_ghos


# Reaction criterion with GHO atoms
class GHOReactionCriterion:
    """
    Reaction criterion based on GHO ghost atoms. A reaction is satisfied when all
    of the specified GHO pair distances are within their cutoffs. This matches the
    reference implementation default, where n_needed equals the number of pairs.
    """

    def __init__(self, pairs: List[Tuple[GHOAtom, GHOAtom, float]]):
        """
        The argument pairs is a list of tuples (gho_mol1, gho_mol2,
        cutoff_distance).
        """
        self.pairs = pairs

    def is_satisfied(
        self,
        rot1: np.ndarray,  # 3x3 rotation matrix for molecule 1
        trans1: np.ndarray,  # length-3 translation for molecule 1
        rot2: np.ndarray,  # 3x3 rotation matrix for molecule 2
        trans2: np.ndarray,  # length-3 translation for molecule 2
    ) -> bool:
        """
        Return True if every GHO pair is within its cutoff distance.
        """
        for gho1, gho2, cutoff in self.pairs:
            d = gho_criterion_distance(gho1, rot1, trans1, gho2, rot2, trans2)
            if d > cutoff:
                return False
        return True

    @classmethod
    def from_rxns_xml(
        cls, rxns_xml_path: str, mol1_ghos: List[GHOAtom], mol2_ghos: List[GHOAtom]
    ) -> "GHOReactionCriterion":
        """
        Build a criterion from the rxns XML using already-parsed GHO atoms.
        """
        pairs = []
        try:
            tree = ET.parse(rxns_xml_path)
            root = tree.getroot()
            for pair_node in root.iter("pair"):
                # Parse the atom1 and atom2 indices and the distance.
                a1_txt = _text(pair_node, "atom1", required=False) or ""
                a2_txt = _text(pair_node, "atom2", required=False) or ""
                dist_txt = _text(pair_node, "distance", required=False) or "5.0"
                try:
                    idx1 = int(a1_txt.strip().split()[0]) if a1_txt.strip() else 0
                    idx2 = int(a2_txt.strip().split()[0]) if a2_txt.strip() else 0
                    cutoff = float(dist_txt.strip())

                    gho1 = next(
                        (g for g in mol1_ghos if g.atom_index == idx1),
                        GHOAtom(idx1, np.zeros(3)),
                    )
                    gho2 = next(
                        (g for g in mol2_ghos if g.atom_index == idx2),
                        GHOAtom(idx2, np.zeros(3)),
                    )
                    pairs.append((gho1, gho2, cutoff))
                except (ValueError, IndexError):
                    continue
        except Exception:
            pass
        return cls(pairs)


# Helpers
def _text(node: ET.Element, tag: str, required: bool = True) -> Optional[str]:
    child = node.find(tag)
    if child is None or child.text is None:
        if required:
            raise ValueError(f"Missing required tag <{tag}> in {node.tag}")
        return None
    return child.text.strip()
